# Generated by Django 5.2.5 on 2025-08-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='project_images/')),
                ('live_link', models.URLField(blank=True, null=True)),
                ('code_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
